// Code generated by protoc-gen-go. DO NOT EDIT.
// source: services.proto

package services

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Assignment struct {
	// message Value {
	//   oneof value {
	//       int32 int32_value   = 1;
	//       string string_value = 2;
	//       float float_value   = 3;
	//       double double_value = 4;
	//       bool bool_value     = 5;
	//   }
	// }
	Variable             string   `protobuf:"bytes,1,opt,name=variable,proto3" json:"variable,omitempty"`
	Value                int32    `protobuf:"varint,2,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Assignment) Reset()         { *m = Assignment{} }
func (m *Assignment) String() string { return proto.CompactTextString(m) }
func (*Assignment) ProtoMessage()    {}
func (*Assignment) Descriptor() ([]byte, []int) {
	return fileDescriptor_8e16ccb8c5307b32, []int{0}
}

func (m *Assignment) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Assignment.Unmarshal(m, b)
}
func (m *Assignment) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Assignment.Marshal(b, m, deterministic)
}
func (m *Assignment) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Assignment.Merge(m, src)
}
func (m *Assignment) XXX_Size() int {
	return xxx_messageInfo_Assignment.Size(m)
}
func (m *Assignment) XXX_DiscardUnknown() {
	xxx_messageInfo_Assignment.DiscardUnknown(m)
}

var xxx_messageInfo_Assignment proto.InternalMessageInfo

func (m *Assignment) GetVariable() string {
	if m != nil {
		return m.Variable
	}
	return ""
}

func (m *Assignment) GetValue() int32 {
	if m != nil {
		return m.Value
	}
	return 0
}

type Status struct {
	IsSuccess            bool     `protobuf:"varint,1,opt,name=is_success,json=isSuccess,proto3" json:"is_success,omitempty"`
	Message              string   `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Status) Reset()         { *m = Status{} }
func (m *Status) String() string { return proto.CompactTextString(m) }
func (*Status) ProtoMessage()    {}
func (*Status) Descriptor() ([]byte, []int) {
	return fileDescriptor_8e16ccb8c5307b32, []int{1}
}

func (m *Status) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Status.Unmarshal(m, b)
}
func (m *Status) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Status.Marshal(b, m, deterministic)
}
func (m *Status) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Status.Merge(m, src)
}
func (m *Status) XXX_Size() int {
	return xxx_messageInfo_Status.Size(m)
}
func (m *Status) XXX_DiscardUnknown() {
	xxx_messageInfo_Status.DiscardUnknown(m)
}

var xxx_messageInfo_Status proto.InternalMessageInfo

func (m *Status) GetIsSuccess() bool {
	if m != nil {
		return m.IsSuccess
	}
	return false
}

func (m *Status) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

type GetVariableRequest struct {
	Variable             string   `protobuf:"bytes,1,opt,name=variable,proto3" json:"variable,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetVariableRequest) Reset()         { *m = GetVariableRequest{} }
func (m *GetVariableRequest) String() string { return proto.CompactTextString(m) }
func (*GetVariableRequest) ProtoMessage()    {}
func (*GetVariableRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_8e16ccb8c5307b32, []int{2}
}

func (m *GetVariableRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetVariableRequest.Unmarshal(m, b)
}
func (m *GetVariableRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetVariableRequest.Marshal(b, m, deterministic)
}
func (m *GetVariableRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetVariableRequest.Merge(m, src)
}
func (m *GetVariableRequest) XXX_Size() int {
	return xxx_messageInfo_GetVariableRequest.Size(m)
}
func (m *GetVariableRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetVariableRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetVariableRequest proto.InternalMessageInfo

func (m *GetVariableRequest) GetVariable() string {
	if m != nil {
		return m.Variable
	}
	return ""
}

type GetVariableResponse struct {
	Assignment           *Assignment `protobuf:"bytes,1,opt,name=assignment,proto3" json:"assignment,omitempty"`
	Status               *Status     `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *GetVariableResponse) Reset()         { *m = GetVariableResponse{} }
func (m *GetVariableResponse) String() string { return proto.CompactTextString(m) }
func (*GetVariableResponse) ProtoMessage()    {}
func (*GetVariableResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_8e16ccb8c5307b32, []int{3}
}

func (m *GetVariableResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetVariableResponse.Unmarshal(m, b)
}
func (m *GetVariableResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetVariableResponse.Marshal(b, m, deterministic)
}
func (m *GetVariableResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetVariableResponse.Merge(m, src)
}
func (m *GetVariableResponse) XXX_Size() int {
	return xxx_messageInfo_GetVariableResponse.Size(m)
}
func (m *GetVariableResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetVariableResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetVariableResponse proto.InternalMessageInfo

func (m *GetVariableResponse) GetAssignment() *Assignment {
	if m != nil {
		return m.Assignment
	}
	return nil
}

func (m *GetVariableResponse) GetStatus() *Status {
	if m != nil {
		return m.Status
	}
	return nil
}

type SetVariableRequest struct {
	Assignment           *Assignment `protobuf:"bytes,1,opt,name=assignment,proto3" json:"assignment,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *SetVariableRequest) Reset()         { *m = SetVariableRequest{} }
func (m *SetVariableRequest) String() string { return proto.CompactTextString(m) }
func (*SetVariableRequest) ProtoMessage()    {}
func (*SetVariableRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_8e16ccb8c5307b32, []int{4}
}

func (m *SetVariableRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SetVariableRequest.Unmarshal(m, b)
}
func (m *SetVariableRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SetVariableRequest.Marshal(b, m, deterministic)
}
func (m *SetVariableRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SetVariableRequest.Merge(m, src)
}
func (m *SetVariableRequest) XXX_Size() int {
	return xxx_messageInfo_SetVariableRequest.Size(m)
}
func (m *SetVariableRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SetVariableRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SetVariableRequest proto.InternalMessageInfo

func (m *SetVariableRequest) GetAssignment() *Assignment {
	if m != nil {
		return m.Assignment
	}
	return nil
}

type SetVariableResponse struct {
	Status               *Status  `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SetVariableResponse) Reset()         { *m = SetVariableResponse{} }
func (m *SetVariableResponse) String() string { return proto.CompactTextString(m) }
func (*SetVariableResponse) ProtoMessage()    {}
func (*SetVariableResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_8e16ccb8c5307b32, []int{5}
}

func (m *SetVariableResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SetVariableResponse.Unmarshal(m, b)
}
func (m *SetVariableResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SetVariableResponse.Marshal(b, m, deterministic)
}
func (m *SetVariableResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SetVariableResponse.Merge(m, src)
}
func (m *SetVariableResponse) XXX_Size() int {
	return xxx_messageInfo_SetVariableResponse.Size(m)
}
func (m *SetVariableResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SetVariableResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SetVariableResponse proto.InternalMessageInfo

func (m *SetVariableResponse) GetStatus() *Status {
	if m != nil {
		return m.Status
	}
	return nil
}

func init() {
	proto.RegisterType((*Assignment)(nil), "services.Assignment")
	proto.RegisterType((*Status)(nil), "services.Status")
	proto.RegisterType((*GetVariableRequest)(nil), "services.GetVariableRequest")
	proto.RegisterType((*GetVariableResponse)(nil), "services.GetVariableResponse")
	proto.RegisterType((*SetVariableRequest)(nil), "services.SetVariableRequest")
	proto.RegisterType((*SetVariableResponse)(nil), "services.SetVariableResponse")
}

func init() { proto.RegisterFile("services.proto", fileDescriptor_8e16ccb8c5307b32) }

var fileDescriptor_8e16ccb8c5307b32 = []byte{
	// 295 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x92, 0x41, 0x4b, 0xc3, 0x40,
	0x10, 0x85, 0x89, 0xd0, 0xda, 0x4c, 0x40, 0x64, 0xdb, 0x43, 0x28, 0x16, 0xca, 0x9e, 0x72, 0x2a,
	0x12, 0x3d, 0x2b, 0x3d, 0x09, 0x01, 0x2f, 0xbb, 0xe2, 0x55, 0xb6, 0x61, 0x2c, 0x0b, 0x49, 0xb6,
	0xee, 0x6c, 0x22, 0xfe, 0x37, 0x7f, 0x9c, 0x90, 0xa4, 0x49, 0xa5, 0x31, 0x07, 0x8f, 0x2f, 0x93,
	0xf7, 0xe6, 0x7d, 0xc3, 0xc2, 0x15, 0xa1, 0xad, 0x74, 0x8a, 0xb4, 0x39, 0x58, 0xe3, 0x0c, 0x9b,
	0x1d, 0x35, 0x7f, 0x00, 0xd8, 0x12, 0xe9, 0x7d, 0x91, 0x63, 0xe1, 0xd8, 0x12, 0x66, 0x95, 0xb2,
	0x5a, 0xed, 0x32, 0x0c, 0xbd, 0xb5, 0x17, 0xf9, 0xa2, 0xd3, 0x6c, 0x01, 0x93, 0x4a, 0x65, 0x25,
	0x86, 0x17, 0x6b, 0x2f, 0x9a, 0x88, 0x46, 0xf0, 0x2d, 0x4c, 0xa5, 0x53, 0xae, 0x24, 0xb6, 0x02,
	0xd0, 0xf4, 0x46, 0x65, 0x9a, 0x22, 0x51, 0xed, 0x9e, 0x09, 0x5f, 0x93, 0x6c, 0x3e, 0xb0, 0x10,
	0x2e, 0x73, 0x24, 0x52, 0xfb, 0x26, 0xc0, 0x17, 0x47, 0xc9, 0x6f, 0x81, 0x3d, 0xa1, 0x7b, 0x6d,
	0xf7, 0x08, 0xfc, 0x28, 0x91, 0x46, 0xab, 0xf0, 0x12, 0xe6, 0xbf, 0x1c, 0x74, 0x30, 0x05, 0x21,
	0xbb, 0x07, 0x50, 0x1d, 0x4b, 0x6d, 0x0a, 0xe2, 0xc5, 0xa6, 0x43, 0xef, 0x39, 0xc5, 0xc9, 0x7f,
	0x2c, 0x82, 0x29, 0xd5, 0x04, 0x75, 0xaf, 0x20, 0xbe, 0xee, 0x1d, 0x0d, 0x99, 0x68, 0xe7, 0x3c,
	0x01, 0x26, 0xcf, 0x8b, 0xfe, 0x6b, 0x2b, 0x7f, 0x84, 0xb9, 0x1c, 0x40, 0xe8, 0xcb, 0x78, 0xe3,
	0x65, 0xe2, 0x6f, 0x0f, 0xb8, 0x34, 0xef, 0xee, 0x53, 0x59, 0x7c, 0xb1, 0xaa, 0x20, 0x95, 0x3a,
	0x6d, 0x0a, 0x95, 0x3d, 0x63, 0x6e, 0xec, 0x97, 0x6c, 0x6c, 0x2c, 0x81, 0xe0, 0xe4, 0x54, 0xec,
	0xa6, 0xcf, 0x3b, 0xbf, 0xf9, 0x72, 0xf5, 0xc7, 0xb4, 0x2d, 0x97, 0x40, 0x20, 0x87, 0xb3, 0xe4,
	0x68, 0xd6, 0x00, 0xe8, 0x6e, 0x5a, 0x3f, 0xc4, 0xbb, 0x9f, 0x00, 0x00, 0x00, 0xff, 0xff, 0xc7,
	0x97, 0xb4, 0xe6, 0x9a, 0x02, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// SoftwareTransactionalMemoryServiceClient is the client API for SoftwareTransactionalMemoryService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type SoftwareTransactionalMemoryServiceClient interface {
	GetVariable(ctx context.Context, in *GetVariableRequest, opts ...grpc.CallOption) (*GetVariableResponse, error)
	SetVariable(ctx context.Context, in *SetVariableRequest, opts ...grpc.CallOption) (*SetVariableResponse, error)
}

type softwareTransactionalMemoryServiceClient struct {
	cc *grpc.ClientConn
}

func NewSoftwareTransactionalMemoryServiceClient(cc *grpc.ClientConn) SoftwareTransactionalMemoryServiceClient {
	return &softwareTransactionalMemoryServiceClient{cc}
}

func (c *softwareTransactionalMemoryServiceClient) GetVariable(ctx context.Context, in *GetVariableRequest, opts ...grpc.CallOption) (*GetVariableResponse, error) {
	out := new(GetVariableResponse)
	err := c.cc.Invoke(ctx, "/services.SoftwareTransactionalMemoryService/GetVariable", in, out, opts...)
	if err != nil {
		fmt.Println(err);
		return nil, err
	}
	return out, nil
}

func (c *softwareTransactionalMemoryServiceClient) SetVariable(ctx context.Context, in *SetVariableRequest, opts ...grpc.CallOption) (*SetVariableResponse, error) {
	out := new(SetVariableResponse)
	err := c.cc.Invoke(ctx, "/services.SoftwareTransactionalMemoryService/SetVariable", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SoftwareTransactionalMemoryServiceServer is the server API for SoftwareTransactionalMemoryService service.
type SoftwareTransactionalMemoryServiceServer interface {
	GetVariable(context.Context, *GetVariableRequest) (*GetVariableResponse, error)
	SetVariable(context.Context, *SetVariableRequest) (*SetVariableResponse, error)
}

// UnimplementedSoftwareTransactionalMemoryServiceServer can be embedded to have forward compatible implementations.
type UnimplementedSoftwareTransactionalMemoryServiceServer struct {
}

func (*UnimplementedSoftwareTransactionalMemoryServiceServer) GetVariable(ctx context.Context, req *GetVariableRequest) (*GetVariableResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetVariable not implemented")
}
func (*UnimplementedSoftwareTransactionalMemoryServiceServer) SetVariable(ctx context.Context, req *SetVariableRequest) (*SetVariableResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SetVariable not implemented")
}

func RegisterSoftwareTransactionalMemoryServiceServer(s *grpc.Server, srv SoftwareTransactionalMemoryServiceServer) {
	s.RegisterService(&_SoftwareTransactionalMemoryService_serviceDesc, srv)
}

func _SoftwareTransactionalMemoryService_GetVariable_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetVariableRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SoftwareTransactionalMemoryServiceServer).GetVariable(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/services.SoftwareTransactionalMemoryService/GetVariable",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SoftwareTransactionalMemoryServiceServer).GetVariable(ctx, req.(*GetVariableRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SoftwareTransactionalMemoryService_SetVariable_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetVariableRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SoftwareTransactionalMemoryServiceServer).SetVariable(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/services.SoftwareTransactionalMemoryService/SetVariable",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SoftwareTransactionalMemoryServiceServer).SetVariable(ctx, req.(*SetVariableRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _SoftwareTransactionalMemoryService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "services.SoftwareTransactionalMemoryService",
	HandlerType: (*SoftwareTransactionalMemoryServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetVariable",
			Handler:    _SoftwareTransactionalMemoryService_GetVariable_Handler,
		},
		{
			MethodName: "SetVariable",
			Handler:    _SoftwareTransactionalMemoryService_SetVariable_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "services.proto",
}
