// Code generated by protoc-gen-go. DO NOT EDIT.
// source: protos/services.proto

package service

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Assignment struct {
	Variable             string            `protobuf:"bytes,1,opt,name=variable,proto3" json:"variable,omitempty"`
	Value                *Assignment_Value `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *Assignment) Reset()         { *m = Assignment{} }
func (m *Assignment) String() string { return proto.CompactTextString(m) }
func (*Assignment) ProtoMessage()    {}
func (*Assignment) Descriptor() ([]byte, []int) {
	return fileDescriptor_edd031a16b9fa047, []int{0}
}

func (m *Assignment) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Assignment.Unmarshal(m, b)
}
func (m *Assignment) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Assignment.Marshal(b, m, deterministic)
}
func (m *Assignment) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Assignment.Merge(m, src)
}
func (m *Assignment) XXX_Size() int {
	return xxx_messageInfo_Assignment.Size(m)
}
func (m *Assignment) XXX_DiscardUnknown() {
	xxx_messageInfo_Assignment.DiscardUnknown(m)
}

var xxx_messageInfo_Assignment proto.InternalMessageInfo

func (m *Assignment) GetVariable() string {
	if m != nil {
		return m.Variable
	}
	return ""
}

func (m *Assignment) GetValue() *Assignment_Value {
	if m != nil {
		return m.Value
	}
	return nil
}

type Assignment_Value struct {
	// Types that are valid to be assigned to Value:
	//	*Assignment_Value_Int32Value
	//	*Assignment_Value_StringValue
	//	*Assignment_Value_FloatValue
	//	*Assignment_Value_DoubleValue
	//	*Assignment_Value_BoolValue
	Value                isAssignment_Value_Value `protobuf_oneof:"value"`
	XXX_NoUnkeyedLiteral struct{}                 `json:"-"`
	XXX_unrecognized     []byte                   `json:"-"`
	XXX_sizecache        int32                    `json:"-"`
}

func (m *Assignment_Value) Reset()         { *m = Assignment_Value{} }
func (m *Assignment_Value) String() string { return proto.CompactTextString(m) }
func (*Assignment_Value) ProtoMessage()    {}
func (*Assignment_Value) Descriptor() ([]byte, []int) {
	return fileDescriptor_edd031a16b9fa047, []int{0, 0}
}

func (m *Assignment_Value) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Assignment_Value.Unmarshal(m, b)
}
func (m *Assignment_Value) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Assignment_Value.Marshal(b, m, deterministic)
}
func (m *Assignment_Value) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Assignment_Value.Merge(m, src)
}
func (m *Assignment_Value) XXX_Size() int {
	return xxx_messageInfo_Assignment_Value.Size(m)
}
func (m *Assignment_Value) XXX_DiscardUnknown() {
	xxx_messageInfo_Assignment_Value.DiscardUnknown(m)
}

var xxx_messageInfo_Assignment_Value proto.InternalMessageInfo

type isAssignment_Value_Value interface {
	isAssignment_Value_Value()
}

type Assignment_Value_Int32Value struct {
	Int32Value int32 `protobuf:"varint,1,opt,name=int32_value,json=int32Value,proto3,oneof"`
}

type Assignment_Value_StringValue struct {
	StringValue string `protobuf:"bytes,2,opt,name=string_value,json=stringValue,proto3,oneof"`
}

type Assignment_Value_FloatValue struct {
	FloatValue float32 `protobuf:"fixed32,3,opt,name=float_value,json=floatValue,proto3,oneof"`
}

type Assignment_Value_DoubleValue struct {
	DoubleValue float64 `protobuf:"fixed64,4,opt,name=double_value,json=doubleValue,proto3,oneof"`
}

type Assignment_Value_BoolValue struct {
	BoolValue bool `protobuf:"varint,5,opt,name=bool_value,json=boolValue,proto3,oneof"`
}

func (*Assignment_Value_Int32Value) isAssignment_Value_Value() {}

func (*Assignment_Value_StringValue) isAssignment_Value_Value() {}

func (*Assignment_Value_FloatValue) isAssignment_Value_Value() {}

func (*Assignment_Value_DoubleValue) isAssignment_Value_Value() {}

func (*Assignment_Value_BoolValue) isAssignment_Value_Value() {}

func (m *Assignment_Value) GetValue() isAssignment_Value_Value {
	if m != nil {
		return m.Value
	}
	return nil
}

func (m *Assignment_Value) GetInt32Value() int32 {
	if x, ok := m.GetValue().(*Assignment_Value_Int32Value); ok {
		return x.Int32Value
	}
	return 0
}

func (m *Assignment_Value) GetStringValue() string {
	if x, ok := m.GetValue().(*Assignment_Value_StringValue); ok {
		return x.StringValue
	}
	return ""
}

func (m *Assignment_Value) GetFloatValue() float32 {
	if x, ok := m.GetValue().(*Assignment_Value_FloatValue); ok {
		return x.FloatValue
	}
	return 0
}

func (m *Assignment_Value) GetDoubleValue() float64 {
	if x, ok := m.GetValue().(*Assignment_Value_DoubleValue); ok {
		return x.DoubleValue
	}
	return 0
}

func (m *Assignment_Value) GetBoolValue() bool {
	if x, ok := m.GetValue().(*Assignment_Value_BoolValue); ok {
		return x.BoolValue
	}
	return false
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*Assignment_Value) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*Assignment_Value_Int32Value)(nil),
		(*Assignment_Value_StringValue)(nil),
		(*Assignment_Value_FloatValue)(nil),
		(*Assignment_Value_DoubleValue)(nil),
		(*Assignment_Value_BoolValue)(nil),
	}
}

type Status struct {
	IsSuccess            bool     `protobuf:"varint,1,opt,name=is_success,json=isSuccess,proto3" json:"is_success,omitempty"`
	Message              string   `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Status) Reset()         { *m = Status{} }
func (m *Status) String() string { return proto.CompactTextString(m) }
func (*Status) ProtoMessage()    {}
func (*Status) Descriptor() ([]byte, []int) {
	return fileDescriptor_edd031a16b9fa047, []int{1}
}

func (m *Status) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Status.Unmarshal(m, b)
}
func (m *Status) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Status.Marshal(b, m, deterministic)
}
func (m *Status) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Status.Merge(m, src)
}
func (m *Status) XXX_Size() int {
	return xxx_messageInfo_Status.Size(m)
}
func (m *Status) XXX_DiscardUnknown() {
	xxx_messageInfo_Status.DiscardUnknown(m)
}

var xxx_messageInfo_Status proto.InternalMessageInfo

func (m *Status) GetIsSuccess() bool {
	if m != nil {
		return m.IsSuccess
	}
	return false
}

func (m *Status) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

type GetVariableReq struct {
	Variable             string   `protobuf:"bytes,1,opt,name=variable,proto3" json:"variable,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetVariableReq) Reset()         { *m = GetVariableReq{} }
func (m *GetVariableReq) String() string { return proto.CompactTextString(m) }
func (*GetVariableReq) ProtoMessage()    {}
func (*GetVariableReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_edd031a16b9fa047, []int{2}
}

func (m *GetVariableReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetVariableReq.Unmarshal(m, b)
}
func (m *GetVariableReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetVariableReq.Marshal(b, m, deterministic)
}
func (m *GetVariableReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetVariableReq.Merge(m, src)
}
func (m *GetVariableReq) XXX_Size() int {
	return xxx_messageInfo_GetVariableReq.Size(m)
}
func (m *GetVariableReq) XXX_DiscardUnknown() {
	xxx_messageInfo_GetVariableReq.DiscardUnknown(m)
}

var xxx_messageInfo_GetVariableReq proto.InternalMessageInfo

func (m *GetVariableReq) GetVariable() string {
	if m != nil {
		return m.Variable
	}
	return ""
}

type GetVariableRes struct {
	Assignment           *Assignment `protobuf:"bytes,1,opt,name=assignment,proto3" json:"assignment,omitempty"`
	Status               *Status     `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *GetVariableRes) Reset()         { *m = GetVariableRes{} }
func (m *GetVariableRes) String() string { return proto.CompactTextString(m) }
func (*GetVariableRes) ProtoMessage()    {}
func (*GetVariableRes) Descriptor() ([]byte, []int) {
	return fileDescriptor_edd031a16b9fa047, []int{3}
}

func (m *GetVariableRes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetVariableRes.Unmarshal(m, b)
}
func (m *GetVariableRes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetVariableRes.Marshal(b, m, deterministic)
}
func (m *GetVariableRes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetVariableRes.Merge(m, src)
}
func (m *GetVariableRes) XXX_Size() int {
	return xxx_messageInfo_GetVariableRes.Size(m)
}
func (m *GetVariableRes) XXX_DiscardUnknown() {
	xxx_messageInfo_GetVariableRes.DiscardUnknown(m)
}

var xxx_messageInfo_GetVariableRes proto.InternalMessageInfo

func (m *GetVariableRes) GetAssignment() *Assignment {
	if m != nil {
		return m.Assignment
	}
	return nil
}

func (m *GetVariableRes) GetStatus() *Status {
	if m != nil {
		return m.Status
	}
	return nil
}

type SetVariableReq struct {
	Assignment           *Assignment `protobuf:"bytes,1,opt,name=assignment,proto3" json:"assignment,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *SetVariableReq) Reset()         { *m = SetVariableReq{} }
func (m *SetVariableReq) String() string { return proto.CompactTextString(m) }
func (*SetVariableReq) ProtoMessage()    {}
func (*SetVariableReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_edd031a16b9fa047, []int{4}
}

func (m *SetVariableReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SetVariableReq.Unmarshal(m, b)
}
func (m *SetVariableReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SetVariableReq.Marshal(b, m, deterministic)
}
func (m *SetVariableReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SetVariableReq.Merge(m, src)
}
func (m *SetVariableReq) XXX_Size() int {
	return xxx_messageInfo_SetVariableReq.Size(m)
}
func (m *SetVariableReq) XXX_DiscardUnknown() {
	xxx_messageInfo_SetVariableReq.DiscardUnknown(m)
}

var xxx_messageInfo_SetVariableReq proto.InternalMessageInfo

func (m *SetVariableReq) GetAssignment() *Assignment {
	if m != nil {
		return m.Assignment
	}
	return nil
}

type SetVariableRes struct {
	Status               *Status  `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SetVariableRes) Reset()         { *m = SetVariableRes{} }
func (m *SetVariableRes) String() string { return proto.CompactTextString(m) }
func (*SetVariableRes) ProtoMessage()    {}
func (*SetVariableRes) Descriptor() ([]byte, []int) {
	return fileDescriptor_edd031a16b9fa047, []int{5}
}

func (m *SetVariableRes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SetVariableRes.Unmarshal(m, b)
}
func (m *SetVariableRes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SetVariableRes.Marshal(b, m, deterministic)
}
func (m *SetVariableRes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SetVariableRes.Merge(m, src)
}
func (m *SetVariableRes) XXX_Size() int {
	return xxx_messageInfo_SetVariableRes.Size(m)
}
func (m *SetVariableRes) XXX_DiscardUnknown() {
	xxx_messageInfo_SetVariableRes.DiscardUnknown(m)
}

var xxx_messageInfo_SetVariableRes proto.InternalMessageInfo

func (m *SetVariableRes) GetStatus() *Status {
	if m != nil {
		return m.Status
	}
	return nil
}

func init() {
	proto.RegisterType((*Assignment)(nil), "service.Assignment")
	proto.RegisterType((*Assignment_Value)(nil), "service.Assignment.Value")
	proto.RegisterType((*Status)(nil), "service.Status")
	proto.RegisterType((*GetVariableReq)(nil), "service.GetVariableReq")
	proto.RegisterType((*GetVariableRes)(nil), "service.GetVariableRes")
	proto.RegisterType((*SetVariableReq)(nil), "service.SetVariableReq")
	proto.RegisterType((*SetVariableRes)(nil), "service.SetVariableRes")
}

func init() { proto.RegisterFile("protos/services.proto", fileDescriptor_edd031a16b9fa047) }

var fileDescriptor_edd031a16b9fa047 = []byte{
	// 397 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x93, 0xcf, 0xaa, 0xd3, 0x40,
	0x14, 0x87, 0x3b, 0xd5, 0xb4, 0xcd, 0x89, 0x54, 0x18, 0x11, 0x6b, 0x41, 0x8c, 0x71, 0x61, 0x16,
	0x92, 0x42, 0xba, 0x72, 0x25, 0x15, 0xc4, 0x6e, 0xdc, 0x4c, 0xa4, 0xdb, 0x32, 0x89, 0xd3, 0x32,
	0x90, 0x66, 0x34, 0x67, 0x52, 0xf1, 0x61, 0xdc, 0xfa, 0x1e, 0xf7, 0xcd, 0x2e, 0x99, 0x99, 0x9b,
	0xfe, 0xa1, 0xed, 0xe2, 0x2e, 0xcf, 0x6f, 0xbe, 0xf9, 0xe6, 0x9c, 0x13, 0x02, 0x2f, 0x7f, 0xd5,
	0x4a, 0x2b, 0x9c, 0xa1, 0xa8, 0xf7, 0xb2, 0x10, 0x98, 0x98, 0x9a, 0x0e, 0x5d, 0x1d, 0xfd, 0xeb,
	0x03, 0x2c, 0x10, 0xe5, 0xb6, 0xda, 0x89, 0x4a, 0xd3, 0x29, 0x8c, 0xf6, 0xbc, 0x96, 0x3c, 0x2f,
	0xc5, 0x84, 0x84, 0x24, 0xf6, 0x59, 0x57, 0xd3, 0x19, 0x78, 0x7b, 0x5e, 0x36, 0x62, 0xd2, 0x0f,
	0x49, 0x1c, 0xa4, 0xaf, 0x13, 0xe7, 0x48, 0x0e, 0xf7, 0x93, 0x55, 0x0b, 0x30, 0xcb, 0x4d, 0xef,
	0x08, 0x78, 0x26, 0xa0, 0xef, 0x20, 0x90, 0x95, 0x9e, 0xa7, 0x6b, 0x2b, 0x68, 0xcd, 0xde, 0xb2,
	0xc7, 0xc0, 0x84, 0x16, 0x79, 0x0f, 0xcf, 0x50, 0xd7, 0xb2, 0xda, 0xae, 0x0f, 0x8f, 0xf8, 0xcb,
	0x1e, 0x0b, 0x6c, 0xda, 0x79, 0x36, 0xa5, 0xe2, 0xda, 0x31, 0x4f, 0x42, 0x12, 0xf7, 0x5b, 0x8f,
	0x09, 0x3b, 0xcf, 0x4f, 0xd5, 0xe4, 0xa5, 0x70, 0xcc, 0xd3, 0x90, 0xc4, 0xa4, 0xf5, 0xd8, 0xd4,
	0x42, 0x6f, 0x01, 0x72, 0xa5, 0x4a, 0x87, 0x78, 0x21, 0x89, 0x47, 0xcb, 0x1e, 0xf3, 0xdb, 0xcc,
	0x00, 0x5f, 0x86, 0x6e, 0xd6, 0x68, 0x01, 0x83, 0x4c, 0x73, 0xdd, 0x20, 0x7d, 0x03, 0x20, 0x71,
	0x8d, 0x4d, 0x51, 0x08, 0x44, 0x33, 0xc2, 0x88, 0xf9, 0x12, 0x33, 0x1b, 0xd0, 0x09, 0x0c, 0x77,
	0x02, 0x91, 0x6f, 0x5d, 0xeb, 0xec, 0xa1, 0x8c, 0x3e, 0xc2, 0xf8, 0x9b, 0xd0, 0x2b, 0xb7, 0x46,
	0x26, 0x7e, 0xdf, 0xda, 0x72, 0x54, 0x9d, 0xd1, 0x48, 0xe7, 0x00, 0xbc, 0xdb, 0xb0, 0xe1, 0x83,
	0xf4, 0xc5, 0x85, 0xe5, 0xb3, 0x23, 0x8c, 0x7e, 0x80, 0x01, 0x9a, 0xbe, 0xdd, 0xd7, 0x7a, 0xde,
	0x5d, 0xb0, 0xe3, 0x30, 0x77, 0x1c, 0x7d, 0x85, 0x71, 0x76, 0xda, 0xdd, 0x63, 0xde, 0x8b, 0x3e,
	0x9d, 0x69, 0xf0, 0xa8, 0x03, 0x72, 0xb3, 0x83, 0xf4, 0x3f, 0x81, 0x28, 0x53, 0x1b, 0xfd, 0x87,
	0xd7, 0xe2, 0x47, 0xcd, 0x2b, 0xe4, 0x85, 0x96, 0xaa, 0xe2, 0xe5, 0x77, 0xb1, 0x53, 0xf5, 0xdf,
	0xcc, 0xde, 0xa2, 0x9f, 0x21, 0x38, 0x5a, 0x0c, 0x7d, 0xd5, 0xe9, 0x4e, 0x97, 0x3b, 0xbd, 0x72,
	0x80, 0xad, 0x20, 0xbb, 0x28, 0xc8, 0xae, 0x09, 0x4e, 0x27, 0xca, 0x07, 0xe6, 0xdf, 0x99, 0xdf,
	0x07, 0x00, 0x00, 0xff, 0xff, 0xa6, 0x4c, 0xb8, 0x49, 0x54, 0x03, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// SoftwareTransactionalMemoryServiceClient is the client API for SoftwareTransactionalMemoryService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type SoftwareTransactionalMemoryServiceClient interface {
	GetVariable(ctx context.Context, in *GetVariableReq, opts ...grpc.CallOption) (*GetVariableRes, error)
	SetVariable(ctx context.Context, in *SetVariableReq, opts ...grpc.CallOption) (*SetVariableRes, error)
}

type softwareTransactionalMemoryServiceClient struct {
	cc *grpc.ClientConn
}

func NewSoftwareTransactionalMemoryServiceClient(cc *grpc.ClientConn) SoftwareTransactionalMemoryServiceClient {
	return &softwareTransactionalMemoryServiceClient{cc}
}

func (c *softwareTransactionalMemoryServiceClient) GetVariable(ctx context.Context, in *GetVariableReq, opts ...grpc.CallOption) (*GetVariableRes, error) {
	out := new(GetVariableRes)
	err := c.cc.Invoke(ctx, "/service.SoftwareTransactionalMemoryService/GetVariable", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *softwareTransactionalMemoryServiceClient) SetVariable(ctx context.Context, in *SetVariableReq, opts ...grpc.CallOption) (*SetVariableRes, error) {
	out := new(SetVariableRes)
	err := c.cc.Invoke(ctx, "/service.SoftwareTransactionalMemoryService/SetVariable", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SoftwareTransactionalMemoryServiceServer is the server API for SoftwareTransactionalMemoryService service.
type SoftwareTransactionalMemoryServiceServer interface {
	GetVariable(context.Context, *GetVariableReq) (*GetVariableRes, error)
	SetVariable(context.Context, *SetVariableReq) (*SetVariableRes, error)
}

// UnimplementedSoftwareTransactionalMemoryServiceServer can be embedded to have forward compatible implementations.
type UnimplementedSoftwareTransactionalMemoryServiceServer struct {
}

func (*UnimplementedSoftwareTransactionalMemoryServiceServer) GetVariable(ctx context.Context, req *GetVariableReq) (*GetVariableRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetVariable not implemented")
}
func (*UnimplementedSoftwareTransactionalMemoryServiceServer) SetVariable(ctx context.Context, req *SetVariableReq) (*SetVariableRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SetVariable not implemented")
}

func RegisterSoftwareTransactionalMemoryServiceServer(s *grpc.Server, srv SoftwareTransactionalMemoryServiceServer) {
	s.RegisterService(&_SoftwareTransactionalMemoryService_serviceDesc, srv)
}

func _SoftwareTransactionalMemoryService_GetVariable_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetVariableReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SoftwareTransactionalMemoryServiceServer).GetVariable(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/service.SoftwareTransactionalMemoryService/GetVariable",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SoftwareTransactionalMemoryServiceServer).GetVariable(ctx, req.(*GetVariableReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _SoftwareTransactionalMemoryService_SetVariable_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetVariableReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SoftwareTransactionalMemoryServiceServer).SetVariable(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/service.SoftwareTransactionalMemoryService/SetVariable",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SoftwareTransactionalMemoryServiceServer).SetVariable(ctx, req.(*SetVariableReq))
	}
	return interceptor(ctx, in, info, handler)
}

var _SoftwareTransactionalMemoryService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "service.SoftwareTransactionalMemoryService",
	HandlerType: (*SoftwareTransactionalMemoryServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetVariable",
			Handler:    _SoftwareTransactionalMemoryService_GetVariable_Handler,
		},
		{
			MethodName: "SetVariable",
			Handler:    _SoftwareTransactionalMemoryService_SetVariable_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "protos/services.proto",
}
