// Code generated by protoc-gen-go. DO NOT EDIT.
// source: services.proto

package services

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// testing just an integer value for now
type Assignment struct {
	// message Value {
	//   oneof value {
	//       int32 int32_value   = 1;
	//       string string_value = 2;
	//       float float_value   = 3;
	//       double double_value = 4;
	//       bool bool_value     = 5;
	//   }
	// }
	Variable             string   `protobuf:"bytes,1,opt,name=variable,proto3" json:"variable,omitempty"`
	Value                int32    `protobuf:"varint,2,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Assignment) Reset()         { *m = Assignment{} }
func (m *Assignment) String() string { return proto.CompactTextString(m) }
func (*Assignment) ProtoMessage()    {}
func (*Assignment) Descriptor() ([]byte, []int) {
	return fileDescriptor_8e16ccb8c5307b32, []int{0}
}

func (m *Assignment) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Assignment.Unmarshal(m, b)
}
func (m *Assignment) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Assignment.Marshal(b, m, deterministic)
}
func (m *Assignment) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Assignment.Merge(m, src)
}
func (m *Assignment) XXX_Size() int {
	return xxx_messageInfo_Assignment.Size(m)
}
func (m *Assignment) XXX_DiscardUnknown() {
	xxx_messageInfo_Assignment.DiscardUnknown(m)
}

var xxx_messageInfo_Assignment proto.InternalMessageInfo

func (m *Assignment) GetVariable() string {
	if m != nil {
		return m.Variable
	}
	return ""
}

func (m *Assignment) GetValue() int32 {
	if m != nil {
		return m.Value
	}
	return 0
}

type Status struct {
	IsSuccess            bool     `protobuf:"varint,1,opt,name=is_success,json=isSuccess,proto3" json:"is_success,omitempty"`
	Message              string   `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Status) Reset()         { *m = Status{} }
func (m *Status) String() string { return proto.CompactTextString(m) }
func (*Status) ProtoMessage()    {}
func (*Status) Descriptor() ([]byte, []int) {
	return fileDescriptor_8e16ccb8c5307b32, []int{1}
}

func (m *Status) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Status.Unmarshal(m, b)
}
func (m *Status) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Status.Marshal(b, m, deterministic)
}
func (m *Status) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Status.Merge(m, src)
}
func (m *Status) XXX_Size() int {
	return xxx_messageInfo_Status.Size(m)
}
func (m *Status) XXX_DiscardUnknown() {
	xxx_messageInfo_Status.DiscardUnknown(m)
}

var xxx_messageInfo_Status proto.InternalMessageInfo

func (m *Status) GetIsSuccess() bool {
	if m != nil {
		return m.IsSuccess
	}
	return false
}

func (m *Status) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

type SessionID struct {
	Key                  string   `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SessionID) Reset()         { *m = SessionID{} }
func (m *SessionID) String() string { return proto.CompactTextString(m) }
func (*SessionID) ProtoMessage()    {}
func (*SessionID) Descriptor() ([]byte, []int) {
	return fileDescriptor_8e16ccb8c5307b32, []int{2}
}

func (m *SessionID) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SessionID.Unmarshal(m, b)
}
func (m *SessionID) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SessionID.Marshal(b, m, deterministic)
}
func (m *SessionID) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SessionID.Merge(m, src)
}
func (m *SessionID) XXX_Size() int {
	return xxx_messageInfo_SessionID.Size(m)
}
func (m *SessionID) XXX_DiscardUnknown() {
	xxx_messageInfo_SessionID.DiscardUnknown(m)
}

var xxx_messageInfo_SessionID proto.InternalMessageInfo

func (m *SessionID) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

// ============ grpc protos for requests and resposnes ============
type GetVariableRequest struct {
	Variable             string     `protobuf:"bytes,1,opt,name=variable,proto3" json:"variable,omitempty"`
	SessionID            *SessionID `protobuf:"bytes,2,opt,name=sessionID,proto3" json:"sessionID,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *GetVariableRequest) Reset()         { *m = GetVariableRequest{} }
func (m *GetVariableRequest) String() string { return proto.CompactTextString(m) }
func (*GetVariableRequest) ProtoMessage()    {}
func (*GetVariableRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_8e16ccb8c5307b32, []int{3}
}

func (m *GetVariableRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetVariableRequest.Unmarshal(m, b)
}
func (m *GetVariableRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetVariableRequest.Marshal(b, m, deterministic)
}
func (m *GetVariableRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetVariableRequest.Merge(m, src)
}
func (m *GetVariableRequest) XXX_Size() int {
	return xxx_messageInfo_GetVariableRequest.Size(m)
}
func (m *GetVariableRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetVariableRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetVariableRequest proto.InternalMessageInfo

func (m *GetVariableRequest) GetVariable() string {
	if m != nil {
		return m.Variable
	}
	return ""
}

func (m *GetVariableRequest) GetSessionID() *SessionID {
	if m != nil {
		return m.SessionID
	}
	return nil
}

type GetVariableResponse struct {
	Assignment           *Assignment `protobuf:"bytes,1,opt,name=assignment,proto3" json:"assignment,omitempty"`
	Status               *Status     `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *GetVariableResponse) Reset()         { *m = GetVariableResponse{} }
func (m *GetVariableResponse) String() string { return proto.CompactTextString(m) }
func (*GetVariableResponse) ProtoMessage()    {}
func (*GetVariableResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_8e16ccb8c5307b32, []int{4}
}

func (m *GetVariableResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetVariableResponse.Unmarshal(m, b)
}
func (m *GetVariableResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetVariableResponse.Marshal(b, m, deterministic)
}
func (m *GetVariableResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetVariableResponse.Merge(m, src)
}
func (m *GetVariableResponse) XXX_Size() int {
	return xxx_messageInfo_GetVariableResponse.Size(m)
}
func (m *GetVariableResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetVariableResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetVariableResponse proto.InternalMessageInfo

func (m *GetVariableResponse) GetAssignment() *Assignment {
	if m != nil {
		return m.Assignment
	}
	return nil
}

func (m *GetVariableResponse) GetStatus() *Status {
	if m != nil {
		return m.Status
	}
	return nil
}

type SetVariableRequest struct {
	Assignment           *Assignment `protobuf:"bytes,1,opt,name=assignment,proto3" json:"assignment,omitempty"`
	SessionID            *SessionID  `protobuf:"bytes,2,opt,name=sessionID,proto3" json:"sessionID,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *SetVariableRequest) Reset()         { *m = SetVariableRequest{} }
func (m *SetVariableRequest) String() string { return proto.CompactTextString(m) }
func (*SetVariableRequest) ProtoMessage()    {}
func (*SetVariableRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_8e16ccb8c5307b32, []int{5}
}

func (m *SetVariableRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SetVariableRequest.Unmarshal(m, b)
}
func (m *SetVariableRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SetVariableRequest.Marshal(b, m, deterministic)
}
func (m *SetVariableRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SetVariableRequest.Merge(m, src)
}
func (m *SetVariableRequest) XXX_Size() int {
	return xxx_messageInfo_SetVariableRequest.Size(m)
}
func (m *SetVariableRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SetVariableRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SetVariableRequest proto.InternalMessageInfo

func (m *SetVariableRequest) GetAssignment() *Assignment {
	if m != nil {
		return m.Assignment
	}
	return nil
}

func (m *SetVariableRequest) GetSessionID() *SessionID {
	if m != nil {
		return m.SessionID
	}
	return nil
}

type SetVariableResponse struct {
	Status               *Status  `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SetVariableResponse) Reset()         { *m = SetVariableResponse{} }
func (m *SetVariableResponse) String() string { return proto.CompactTextString(m) }
func (*SetVariableResponse) ProtoMessage()    {}
func (*SetVariableResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_8e16ccb8c5307b32, []int{6}
}

func (m *SetVariableResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SetVariableResponse.Unmarshal(m, b)
}
func (m *SetVariableResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SetVariableResponse.Marshal(b, m, deterministic)
}
func (m *SetVariableResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SetVariableResponse.Merge(m, src)
}
func (m *SetVariableResponse) XXX_Size() int {
	return xxx_messageInfo_SetVariableResponse.Size(m)
}
func (m *SetVariableResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SetVariableResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SetVariableResponse proto.InternalMessageInfo

func (m *SetVariableResponse) GetStatus() *Status {
	if m != nil {
		return m.Status
	}
	return nil
}

type CreateSessionRequest struct {
	Status               *Status  `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateSessionRequest) Reset()         { *m = CreateSessionRequest{} }
func (m *CreateSessionRequest) String() string { return proto.CompactTextString(m) }
func (*CreateSessionRequest) ProtoMessage()    {}
func (*CreateSessionRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_8e16ccb8c5307b32, []int{7}
}

func (m *CreateSessionRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateSessionRequest.Unmarshal(m, b)
}
func (m *CreateSessionRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateSessionRequest.Marshal(b, m, deterministic)
}
func (m *CreateSessionRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateSessionRequest.Merge(m, src)
}
func (m *CreateSessionRequest) XXX_Size() int {
	return xxx_messageInfo_CreateSessionRequest.Size(m)
}
func (m *CreateSessionRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateSessionRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateSessionRequest proto.InternalMessageInfo

func (m *CreateSessionRequest) GetStatus() *Status {
	if m != nil {
		return m.Status
	}
	return nil
}

type CreateSessionResponse struct {
	SessionID            *SessionID `protobuf:"bytes,1,opt,name=sessionID,proto3" json:"sessionID,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *CreateSessionResponse) Reset()         { *m = CreateSessionResponse{} }
func (m *CreateSessionResponse) String() string { return proto.CompactTextString(m) }
func (*CreateSessionResponse) ProtoMessage()    {}
func (*CreateSessionResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_8e16ccb8c5307b32, []int{8}
}

func (m *CreateSessionResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateSessionResponse.Unmarshal(m, b)
}
func (m *CreateSessionResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateSessionResponse.Marshal(b, m, deterministic)
}
func (m *CreateSessionResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateSessionResponse.Merge(m, src)
}
func (m *CreateSessionResponse) XXX_Size() int {
	return xxx_messageInfo_CreateSessionResponse.Size(m)
}
func (m *CreateSessionResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateSessionResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreateSessionResponse proto.InternalMessageInfo

func (m *CreateSessionResponse) GetSessionID() *SessionID {
	if m != nil {
		return m.SessionID
	}
	return nil
}

type CommitSessionRequest struct {
	SessionID            *SessionID `protobuf:"bytes,1,opt,name=sessionID,proto3" json:"sessionID,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *CommitSessionRequest) Reset()         { *m = CommitSessionRequest{} }
func (m *CommitSessionRequest) String() string { return proto.CompactTextString(m) }
func (*CommitSessionRequest) ProtoMessage()    {}
func (*CommitSessionRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_8e16ccb8c5307b32, []int{9}
}

func (m *CommitSessionRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CommitSessionRequest.Unmarshal(m, b)
}
func (m *CommitSessionRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CommitSessionRequest.Marshal(b, m, deterministic)
}
func (m *CommitSessionRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CommitSessionRequest.Merge(m, src)
}
func (m *CommitSessionRequest) XXX_Size() int {
	return xxx_messageInfo_CommitSessionRequest.Size(m)
}
func (m *CommitSessionRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CommitSessionRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CommitSessionRequest proto.InternalMessageInfo

func (m *CommitSessionRequest) GetSessionID() *SessionID {
	if m != nil {
		return m.SessionID
	}
	return nil
}

type CommitSessionResponse struct {
	Status               *Status  `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CommitSessionResponse) Reset()         { *m = CommitSessionResponse{} }
func (m *CommitSessionResponse) String() string { return proto.CompactTextString(m) }
func (*CommitSessionResponse) ProtoMessage()    {}
func (*CommitSessionResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_8e16ccb8c5307b32, []int{10}
}

func (m *CommitSessionResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CommitSessionResponse.Unmarshal(m, b)
}
func (m *CommitSessionResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CommitSessionResponse.Marshal(b, m, deterministic)
}
func (m *CommitSessionResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CommitSessionResponse.Merge(m, src)
}
func (m *CommitSessionResponse) XXX_Size() int {
	return xxx_messageInfo_CommitSessionResponse.Size(m)
}
func (m *CommitSessionResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CommitSessionResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CommitSessionResponse proto.InternalMessageInfo

func (m *CommitSessionResponse) GetStatus() *Status {
	if m != nil {
		return m.Status
	}
	return nil
}

func init() {
	proto.RegisterType((*Assignment)(nil), "services.Assignment")
	proto.RegisterType((*Status)(nil), "services.Status")
	proto.RegisterType((*SessionID)(nil), "services.SessionID")
	proto.RegisterType((*GetVariableRequest)(nil), "services.GetVariableRequest")
	proto.RegisterType((*GetVariableResponse)(nil), "services.GetVariableResponse")
	proto.RegisterType((*SetVariableRequest)(nil), "services.SetVariableRequest")
	proto.RegisterType((*SetVariableResponse)(nil), "services.SetVariableResponse")
	proto.RegisterType((*CreateSessionRequest)(nil), "services.CreateSessionRequest")
	proto.RegisterType((*CreateSessionResponse)(nil), "services.CreateSessionResponse")
	proto.RegisterType((*CommitSessionRequest)(nil), "services.CommitSessionRequest")
	proto.RegisterType((*CommitSessionResponse)(nil), "services.CommitSessionResponse")
}

func init() { proto.RegisterFile("services.proto", fileDescriptor_8e16ccb8c5307b32) }

var fileDescriptor_8e16ccb8c5307b32 = []byte{
	// 416 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x94, 0x4d, 0xef, 0xd2, 0x40,
	0x10, 0xc6, 0xd3, 0xbf, 0x01, 0xe9, 0x54, 0x0d, 0x59, 0x4a, 0x42, 0x88, 0x28, 0xe9, 0x89, 0x13,
	0x46, 0xf4, 0xac, 0x22, 0x26, 0x06, 0x12, 0x13, 0xb3, 0x6b, 0x3c, 0x78, 0x31, 0x4b, 0x33, 0x92,
	0x8d, 0xb4, 0x8b, 0x9d, 0x2d, 0x86, 0x83, 0xdf, 0xd5, 0x8f, 0x62, 0xec, 0x7b, 0xa1, 0x20, 0x72,
	0xeb, 0xec, 0xce, 0xfe, 0x9e, 0x67, 0x5e, 0x52, 0x78, 0x44, 0x18, 0xed, 0x95, 0x8f, 0x34, 0xdd,
	0x45, 0xda, 0x68, 0xd6, 0xc9, 0x63, 0xef, 0x15, 0xc0, 0x9c, 0x48, 0x6d, 0xc2, 0x00, 0x43, 0xc3,
	0x86, 0xd0, 0xd9, 0xcb, 0x48, 0xc9, 0xf5, 0x16, 0x07, 0xd6, 0xd8, 0x9a, 0xd8, 0xbc, 0x88, 0x99,
	0x0b, 0xad, 0xbd, 0xdc, 0xc6, 0x38, 0xb8, 0x1b, 0x5b, 0x93, 0x16, 0x4f, 0x03, 0x6f, 0x0e, 0x6d,
	0x61, 0xa4, 0x89, 0x89, 0x8d, 0x00, 0x14, 0x7d, 0xa5, 0xd8, 0xf7, 0x91, 0x28, 0x79, 0xdd, 0xe1,
	0xb6, 0x22, 0x91, 0x1e, 0xb0, 0x01, 0xdc, 0x0f, 0x90, 0x48, 0x6e, 0x52, 0x80, 0xcd, 0xf3, 0xd0,
	0x1b, 0x81, 0x2d, 0x90, 0x48, 0xe9, 0x70, 0xf9, 0x8e, 0x75, 0xe1, 0xde, 0x77, 0x3c, 0x64, 0xe2,
	0x7f, 0x3f, 0x3d, 0x1f, 0xd8, 0x7b, 0x34, 0x9f, 0x33, 0x1b, 0x1c, 0x7f, 0xc4, 0x48, 0x97, 0x9d,
	0x3e, 0x07, 0x9b, 0x72, 0x60, 0x22, 0xe6, 0xcc, 0x7a, 0xd3, 0xa2, 0x03, 0x85, 0x16, 0x2f, 0xb3,
	0xbc, 0x18, 0x7a, 0x35, 0x11, 0xda, 0xe9, 0x90, 0x90, 0xbd, 0x04, 0x90, 0x45, 0x77, 0x12, 0x1d,
	0x67, 0xe6, 0x96, 0xa8, 0xb2, 0x73, 0xbc, 0x92, 0xc7, 0x26, 0xd0, 0xa6, 0xa4, 0x27, 0x99, 0x78,
	0xb7, 0x22, 0x9e, 0x9c, 0xf3, 0xec, 0xde, 0xfb, 0x05, 0x4c, 0x9c, 0xd6, 0x76, 0x9b, 0xea, 0x0d,
	0x55, 0xbf, 0x86, 0x9e, 0x68, 0xa8, 0xba, 0xf4, 0x6f, 0xfd, 0xc3, 0xff, 0x1b, 0x70, 0x17, 0x11,
	0x4a, 0x83, 0x19, 0x3e, 0xaf, 0xe0, 0x7a, 0xc2, 0x0a, 0xfa, 0x47, 0x84, 0xcc, 0x44, 0xad, 0x1c,
	0xeb, 0xaa, 0x72, 0x96, 0xe0, 0x2e, 0x74, 0x10, 0x28, 0x73, 0xe4, 0xe6, 0x06, 0xd4, 0x1c, 0xfa,
	0x47, 0xa8, 0xff, 0xed, 0xcd, 0xec, 0xf7, 0x1d, 0x78, 0x42, 0x7f, 0x33, 0x3f, 0x65, 0x84, 0x9f,
	0x22, 0x19, 0x92, 0xf4, 0x8d, 0xd2, 0xa1, 0xdc, 0x7e, 0xc0, 0x40, 0x47, 0x07, 0x91, 0x3e, 0x63,
	0x2b, 0x70, 0x2a, 0x9b, 0xc7, 0x1e, 0x97, 0xbc, 0xd3, 0xad, 0x1f, 0x8e, 0xce, 0xdc, 0x66, 0xe6,
	0x56, 0xe0, 0x88, 0x66, 0x96, 0xb8, 0xc8, 0x6a, 0x5a, 0x82, 0x8f, 0xf0, 0xb0, 0x36, 0x18, 0xf6,
	0xa4, 0xcc, 0x6f, 0x9a, 0xf9, 0xf0, 0xe9, 0xd9, 0xfb, 0x0a, 0xb1, 0xda, 0xd3, 0x1a, 0xb1, 0x61,
	0x6e, 0x35, 0x62, 0xd3, 0x30, 0xde, 0x3e, 0xf8, 0x02, 0xd3, 0x67, 0x79, 0xce, 0xba, 0x9d, 0xfc,
	0xdb, 0x5e, 0xfc, 0x09, 0x00, 0x00, 0xff, 0xff, 0xcd, 0xa0, 0x4f, 0x7f, 0xed, 0x04, 0x00, 0x00,
}
